### Отримати всі нотатки
GET http://localhost:3000/api/perfumes
### Отримати нотатку за id (підставте реальний id)
GET http://localhost:3000/api/perfumes/6ab55b3cd242a29a73ddba62
### Створити нову нотатку
POST http://localhost:3000/api/perfumes
Content-Type: application/json

{
    "name": "Chanel No. 5",
    "brand": "Chanel",
    "description": "Класичний квітково-альдегідний аромат",
    "price": 4500,
    "volume": 50
}
### Оновити нотатку (підставте реальний id)
PUT http://localhost:3000/api/perfumes/6ab55b3cd242a29a73ddba62
Content-Type: application/json

{
    "name": "Chanel No. 5 Red Edition",
    "brand": "Chanel",
    "description": "Оновлений класичний аромат у червоному флаконі",
    "price": 5200,
    "volume": 100
}
### Видалити нотатку (підставте реальний id)
DELETE http://localhost:3000/api/perfumes/6ab55b3cd242a29a73ddba62